[package]
name = "json-liquid-rs"
version = "1.0.0"
edition = "2021"

[dependencies]
liquid-json = { version = "0.6.1", default-features = false }
serde_json = { version = "1.0.125", default-features = false }
